# Generated by Django 4.2.16 on 2025-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
