# Generated by Django 4.2.16 on 2025-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_produto_estoque_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(blank=True),
        ),
    ]
