# Generated by Django 5.1.4 on 2025-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_produto_img_base64'),
        ('home', '0007_alter_itempedido_pedido'),
    ]

    operations = [
    ]
